name: 'Publish application'
on: push

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    env:
     PUBLISH_FOLDER: src/RoseBingo/Client/bin/Release/net7.0/publish/wwwroot
    name: Build and Deploy Job
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      
      - name: Build
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - run: dotnet publish src/RoseBingo/Client/RoseBingo.Client.csproj -c Release

      - name: Adapt some files
      - run: sed -i 's/<base href="\/" \/>/<base href="\/${{ env.REPO_NAME }}\/" \/>/g' $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html
      - run: cp $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html $GITHUB_WORKSPACE/$PUBLISH_FOLDER/404.html
      - run: touch $PUBLISH_FOLDER/.nojekyll

      - name: Deploy GitHub Pages action
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
            github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_branch: gh-pages
            publish_dir: /${{ env.PUBLISH_FOLDER }}
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
